version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_database'
    environment:
      - MONGO_INITDB_DATABASE=hydrogen
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - ./mongo_volume:/data/db/
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017